
-- Insert more beautiful hotels that won't be featured
INSERT INTO public.properties (
  title,
  description,
  location,
  price_per_night,
  max_guests,
  bedrooms,
  bathrooms,
  amenities,
  images,
  latitude,
  longitude,
  available,
  host_id
) VALUES 
(
  'Luxury Treehouse Resort',
  'Unique elevated treehouse experience in the lush forests of Wayanad. Perfect blend of luxury and nature with panoramic forest views.',
  'Wayanad, Kerala',
  320,
  4,
  2,
  2,
  ARRAY['WiFi', 'Forest View', 'Spa', 'Nature Walks', 'Organic Restaurant'],
  ARRAY['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=500&h=300&fit=crop'],
  11.6854,
  76.1320,
  true,
  null
),
(
  'Desert Glamping Experience',
  'Luxurious tent accommodation in the Thar Desert with camel safaris and traditional Rajasthani cultural performances.',
  'Jaisalmer, Rajasthan',
  280,
  6,
  3,
  2,
  ARRAY['WiFi', 'Desert View', 'Camel Safari', 'Cultural Shows', 'Star Gazing'],
  ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=300&fit=crop'],
  26.9157,
  70.9083,
  true,
  null
),
(
  'Coastal Cliff Villa',
  'Spectacular clifftop villa overlooking the Arabian Sea in Varkala with private infinity pool and yoga deck.',
  'Varkala, Kerala',
  450,
  8,
  4,
  3,
  ARRAY['WiFi', 'Ocean View', 'Infinity Pool', 'Yoga Deck', 'Private Chef'],
  ARRAY['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500&h=300&fit=crop'],
  8.7335,
  76.7163,
  true,
  null
),
(
  'Alpine Chalet Retreat',
  'Cozy Swiss-style chalet in Gulmarg with skiing facilities and breathtaking views of snow-capped mountains.',
  'Gulmarg, Kashmir',
  380,
  6,
  3,
  2,
  ARRAY['WiFi', 'Mountain View', 'Skiing', 'Fireplace', 'Hot Chocolate Service'],
  ARRAY['https://images.unsplash.com/photo-1551524164-6cf2ac58e608?w=500&h=300&fit=crop'],
  34.0484,
  74.3894,
  true,
  null
),
(
  'Heritage Fort Palace',
  'Converted 15th-century fort palace in Jodhpur offering royal heritage experience with traditional Rajasthani hospitality.',
  'Jodhpur, Rajasthan',
  520,
  10,
  5,
  4,
  ARRAY['WiFi', 'Heritage Architecture', 'Royal Dining', 'Cultural Tours', 'Vintage Car Rides'],
  ARRAY['https://images.unsplash.com/photo-1590073844006-33379778ae09?w=500&h=300&fit=crop'],
  26.2389,
  73.0243,
  true,
  null
),
(
  'Tea Estate Bungalow',
  'Colonial-era tea planter bungalow in Darjeeling with stunning Himalayan views and tea garden tours.',
  'Darjeeling, West Bengal',
  240,
  6,
  3,
  2,
  ARRAY['WiFi', 'Mountain View', 'Tea Gardens', 'Colonial Architecture', 'Tea Tasting'],
  ARRAY['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=500&h=300&fit=crop'],
  27.0410,
  88.2663,
  true,
  null
);
