
-- Insert Indian hotels/properties
INSERT INTO public.properties (
  title,
  description,
  location,
  price_per_night,
  max_guests,
  bedrooms,
  bathrooms,
  amenities,
  images,
  latitude,
  longitude,
  available,
  host_id
) VALUES 
(
  'Heritage Haveli in Old Delhi',
  'Experience authentic Mughal architecture in this beautifully restored haveli. Located in the heart of Old Delhi, steps away from Red Fort and Jama Masjid.',
  'Old Delhi, Delhi',
  125,
  6,
  3,
  2,
  ARRAY['WiFi', 'AC', 'Traditional Decor', 'Rooftop Terrace', 'Heritage Architecture'],
  ARRAY['https://images.unsplash.com/photo-1590073844006-33379778ae09?w=500&h=300&fit=crop'],
  28.6562,
  77.2410,
  true,
  null
),
(
  'Kerala Backwater Houseboat',
  'Float through the serene backwaters of Alleppey in this traditional Kerala houseboat. Includes all meals and guided tours.',
  'Alleppey, Kerala',
  180,
  4,
  2,
  1,
  ARRAY['WiFi', 'All Meals Included', 'AC', 'Traditional Kerala Cuisine', 'Guided Tours'],
  ARRAY['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=500&h=300&fit=crop'],
  9.4981,
  76.3388,
  true,
  null
),
(
  'Rajasthani Palace Suite',
  'Live like royalty in this opulent palace suite in Udaipur. Overlooking Lake Pichola with stunning views of the City Palace.',
  'Udaipur, Rajasthan',
  350,
  4,
  2,
  2,
  ARRAY['WiFi', 'Lake View', 'Royal Decor', 'Butler Service', 'Spa Access'],
  ARRAY['https://images.unsplash.com/photo-1587474260584-136574528ed5?w=500&h=300&fit=crop'],
  24.5854,
  73.7125,
  true,
  null
),
(
  'Goan Beach Villa',
  'Stunning beachfront villa in North Goa with private beach access. Perfect for groups looking for sun, sand, and relaxation.',
  'Calangute, Goa',
  220,
  8,
  4,
  3,
  ARRAY['WiFi', 'Private Beach', 'Pool', 'BBQ Area', 'Water Sports'],
  ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=300&fit=crop'],
  15.5530,
  73.7690,
  true,
  null
),
(
  'Himalayan Mountain Retreat',
  'Escape to the mountains in this cozy retreat in Manali. Surrounded by snow-capped peaks and pine forests.',
  'Manali, Himachal Pradesh',
  95,
  6,
  3,
  2,
  ARRAY['WiFi', 'Mountain View', 'Fireplace', 'Trekking Guides', 'Bonfire Area'],
  ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=300&fit=crop'],
  32.2396,
  77.1887,
  true,
  null
),
(
  'Mumbai Luxury Apartment',
  'Modern luxury apartment in Bandra with stunning views of the Arabian Sea. Close to Bollywood studios and trendy cafes.',
  'Bandra, Mumbai',
  275,
  4,
  2,
  2,
  ARRAY['WiFi', 'Sea View', 'Gym', 'Swimming Pool', 'Concierge'],
  ARRAY['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=500&h=300&fit=crop'],
  19.0596,
  72.8295,
  true,
  null
);
