// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aggfkprpkgbrxyfyiuoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZ2ZrcHJwa2dicnh5ZnlpdW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDA1MzksImV4cCI6MjA2NTM3NjUzOX0.6aDn-bneVpY_y2TSm4uNuQB53s_Yu-yg3BSiPb87FCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);